console.log("avanzar");
console.log("eliminar");
console.log("avanzar");
console.log("eliminar");
console.log("avanzar");
console.log("eliminar");
console.log("avanzar");
console.log("eliminar");
console.log("girar a la izquierda");
console.log("avanzar");
console.log("eliminar");
console.log("avanzar");
console.log("eliminar");
console.log("avanzar");
console.log("eliminar");
console.log("avanzar");
console.log("eliminar");
console.log("avanzar");
console.log("eliminar");
console.log("tarea finalizada");
